#!/bin/sh

echo -n ${PREVIEW_REPOSITORY_URL} > /app/images/preview_target_repository
echo -n ${MAX_CONTAINERS} > /app/images/max_containers

chown root:docker /var/run/docker.sock && \
chmod 775 /var/run/docker.sock && \
service crond start && \
service httpd start && \
service supervisord start
