#!/bin/sh

# setup private key if exists
GITHUB_PRIVATE_KEY="/app/keys/id_rsa"
APACHE_SSH_DIR="/var/www/.ssh"
ROOT_SSH_DIR="/root/.ssh"

if [ -f ${GITHUB_PRIVATE_KEY} ]; then
    cp ${GITHUB_PRIVATE_KEY} ${APACHE_SSH_DIR}/
    chmod 600 ${APACHE_SSH_DIR}/$(basename ${GITHUB_PRIVATE_KEY})
    chown apache. ${APACHE_SSH_DIR}/$(basename ${GITHUB_PRIVATE_KEY})

    cp ${GITHUB_PRIVATE_KEY} ${ROOT_SSH_DIR}/
    chmod 600 ${ROOT_SSH_DIR}/$(basename ${GITHUB_PRIVATE_KEY})
fi

# setup pool variables
echo -n ${PREVIEW_REPOSITORY_URL} > /app/images/preview_target_repository
echo -n ${MAX_CONTAINERS} > /app/images/max_containers
echo -n ${POOL_BASE_DOMAIN} > /app/images/base_domain

# setup hosts file
echo ${POOL_BASE_DOMAIN} >> /etc/hosts

chown root:docker /var/run/docker.sock && \
chmod 775 /var/run/docker.sock && \
/etc/init.d/redis start && \
service crond start && \
service httpd start && \
supervisord -c /etc/supervisord.conf

if [[ ${GITHUB_BOT} = "true" ]]; then
    supervisorctl start github_bot
fi
