#!/bin/sh -xe
# Setup script for pool host
# NOTE: Run it as root

GITHUB_BOT=false

# options may be followed by one colon to indicate they have a required argument
if ! options=$(getopt -u -o g -l github-bot -- "$@")
then
    # something went wrong, getopt will put out an error message for us
    exit 1
fi

set -- $options

while [ $# -gt 0 ]
do
    case $1 in
    -g | --github-bot) GITHUB_BOT=true ;;
    (--) shift; break;;
    (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    (*) break;;
    esac
    shift
done

# pass arguments to pool config vars
PREVIEW_REPOSITORY_URL=${1:-https://github.com/mookjp/flaskapp.git}
MAX_CONTAINERS=${2:-5}
POOL_BASE_DOMAIN=${3:-pool.dev}
GITHUB_BOT=${GITHUB_BOT:-false}

cd /tmp
mkdir -p /opt/pool/bin
export POOL_BIN_PATH=/opt/pool/bin
export PATH=${POOL_BIN_PATH}:$PATH:/usr/local/bin

if [ $(which systemctl) ]; then
    echo "systemd detected. Updating to latest docker.."
    systemctl stop docker
    wget -q https://get.docker.com/builds/Linux/x86_64/docker-latest -O ${POOL_BIN_PATH}/docker
    chmod +x ${POOL_BIN_PATH}/docker
    cat << EOF > /etc/systemd/system/docker.service
.include /usr/lib/systemd/system/docker.service

[Service]
ExecStart=
ExecStart=${POOL_BIN_PATH}/docker -d
EOF
    systemctl daemon-reload
    systemctl enable docker
    systemctl start docker
else
    echo "NOTICE:"
    echo "This system does not have systemd and docker was not updated
    automatically."
    echo "pool container uses the latest docker."
    echo "If docker on host is not the latest version, pool may not work
    correctly as it can not communicate between host and containers."
fi

# load cache images on local if it exists (for speed to build vagrant)
# If you want to use cache, execute below commands to pull pool-base
# image and load it to vagrant VM:
# $ docker pull prevsio/pool-base && docker save prevsio/pool-base > images/pool-base.tar

IMAGE_POOL_BASE="/app/images/pool-base.tar"
if [[ -f  ${IMAGE_POOL_BASE} ]]; then
    # wait docker daemon ready
    sleep 3
    docker load < ${IMAGE_POOL_BASE} 
fi

# Add mantainance script to log in to docker
wget -q https://raw.githubusercontent.com/jpetazzo/nsenter/master/docker-enter -O ${POOL_BIN_PATH}/docker-enter
chmod +x ${POOL_BIN_PATH}/docker-enter

# build build-server
cd /app/docker/pool
docker build -t pool-server .
docker run -d -v /var/run/docker.sock:/var/run/docker.sock \
              --env MAX_CONTAINERS=${MAX_CONTAINERS} \
              --env PREVIEW_REPOSITORY_URL=${PREVIEW_REPOSITORY_URL} \
              --env POOL_BASE_DOMAIN=${POOL_BASE_DOMAIN} \
              --env GITHUB_BOT=${GITHUB_BOT} \
              --name pool -p 80:80 pool-server
hostname pool
