#!/bin/sh
# Setup script for pool host

# pass arguments to pool config vars
PREVIEW_REPOSITORY_URL=${1:-https://github.com/mookjp/flaskapp.git}
MAX_CONTAINERS=${2:-5}
POOL_BASE_DOMAIN=${3:-pool.dev}

export PATH=$PATH:/usr/local/bin
cd /tmp

# Restart docker with remote API
cp /app/provisioning/docker-tcp.socket /etc/systemd/system/docker-tcp.socket
systemctl enable docker-tcp.socket
sudo systemctl enable docker-tcp.socket
sudo systemctl stop docker
sudo systemctl start docker-tcp.socket
sudo systemctl start docker

# load cache images on local if it exists (for speed to build vagrant)
IMAGE_APACHE_MOD_MRUBY="/app/images/apache-mod-mruby.tar"
if [[ -f  ${IMAGE_APACHE_MOD_MRUBY} ]]; then
    sudo docker load < ${IMAGE_APACHE_MOD_MRUBY} 
fi

# Add mantainance script to log in to docker
mkdir -p /app/vendor/scripts
wget -q https://raw.githubusercontent.com/jpetazzo/nsenter/master/docker-enter -O /app/vendor/scripts/docker-enter
chmod +x /app/vendor/scripts/docker-enter

# build build-server
cd /app/docker/pool
docker build -t pool-server .
docker run -d -v /var/run/docker.sock:/var/run/docker.sock \
              --env MAX_CONTAINERS=${MAX_CONTAINERS} \
              --env PREVIEW_REPOSITORY_URL=${PREVIEW_REPOSITORY_URL} \
              --env POOL_BASE_DOMAIN=${POOL_BASE_DOMAIN} \
              --name pool -p 80:80 -p 8080:8080 pool-server
hostname pool
