require 'rake'
require 'rspec/core/rake_task'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  serverspec = []
  Dir.glob('./spec/serverspec/*').each do |dir|
    next unless File.directory?(dir)
    serverspec << File.basename(dir)
  end

  task :all     => [serverspec, :infrataster].flatten
  task :default => :all

  serverspec.each do |target|
    desc "Run serverspec tests to #{target}"
    RSpec::Core::RakeTask.new(target.to_sym) do |t|
      ENV['TARGET_HOST'] = target
      t.pattern = "spec/serverspec/#{target}/*_spec.rb"
    end
  end

  RSpec::Core::RakeTask.new(:infrataster) do |t|
      desc "Run infrataster tests"
      t.pattern = "spec/infrataster/*_spec.rb"
  end
end
